services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
        - "8001:8001"
    volumes:
      - redis-data:/data
    networks:
      - wouri-net

  rabbitmq:
    image: rabbitmq:3.9.28-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - wouri-net
volumes:
  redis-data:
  rabbitmq-data:

networks:
    wouri-net:
      driver: bridge